version: 2
updates:
  - package-ecosystem: 'pip'
    directory: '/'
    open-pull-requests-limit: 100
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'npm'
    directory: '/docs/'
    open-pull-requests-limit: 100
    schedule:
      interval: 'monthly'
