import enum


class YamlModelType(str, enum.Enum):
    COMPRESSOR_WITH_TURBINE = "COMPRESSOR_WITH_TURBINE"
    COMPRESSOR_CHART = "COMPRESSOR_CHART"
    TURBINE = "TURBINE"
    FLUID = "FLUID"


class YamlChartType(str, enum.Enum):
    VARIABLE_SPEED = "VARIABLE_SPEED"
    GENERIC_FROM_INPUT = "GENERIC_FROM_INPUT"
    GENERIC_FROM_DESIGN_POINT = "GENERIC_FROM_DESIGN_POINT"
