from enum import StrEnum


class ChartType(StrEnum):
    SINGLE_SPEED = "SINGLE_SPEED_CHART"
    VARIABLE_SPEED = "VARIABLE_SPEED_CHART"
    GENERIC_FROM_DESIGN_POINT = "GENERIC_CHART_FROM_DESIGN_POINT"
    GENERIC_FROM_INPUT = "GENERIC_CHART_FROM_INPUT"
