from enum import Enum


class FixedSpeedPressureControl(str, Enum):
    UPSTREAM_CHOKE = "UPSTREAM_CHOKE"
    DOWNSTREAM_CHOKE = "DOWNSTREAM_CHOKE"
    INDIVIDUAL_ASV_PRESSURE = "INDIVIDUAL_ASV_PRESSURE"
    INDIVIDUAL_ASV_RATE = "INDIVIDUAL_ASV_RATE"
    COMMON_ASV = "COMMON_ASV"
