import enum


class YamlFacilityModelType(str, enum.Enum):
    ELECTRICITY2FUEL = "ELECTRICITY2FUEL"
    TABULAR = "TABULAR"
    COMPRESSOR_TABULAR = "COMPRESSOR_TABULAR"
    PUMP_CHART_SINGLE_SPEED = "PUMP_CHART_SINGLE_SPEED"
    PUMP_CHART_VARIABLE_SPEED = "PUMP_CHART_VARIABLE_SPEED"
