name: Generate documentation

on:
  # Workflow dispatch is used for manual triggers
  workflow_dispatch:
  # Workflow call is used for called from another workflow
  workflow_call:

env:
  GITHUB_PAGES_BRANCH: gh-pages

jobs:
  publish-docs:
    runs-on: ubuntu-24.04

    environment:
      name: docs-prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Poetry
        run: pipx install poetry==1.8.4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'poetry'

      - name: Check pyproject.toml validity
        run: poetry check --no-interaction

      - name: Install deps
        run: poetry install --no-interaction

      - name: Generate CLI reference
        run: |
          poetry run typer src/ecalc_cli/main.py utils docs > ./docs/docs/about/getting_started/cli/cli_reference.md

      - name: Generate JSON Schema
        run: |
          cd src
          poetry run python generate_json_schema.py > ../docs/docs/about/getting_started/yaml/ecalc_json_schema.json

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: docs/package-lock.json

      - name: Install dependencies and build website
        run: |
          cd docs
          npm ci --ignore-scripts
          npm run build

      - name: Push static files to Github Pages branch
        run: |
          cd docs/build
          CREATED_FROM_REF=$(git rev-parse --short HEAD)
          git init
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git checkout -b $GITHUB_PAGES_BRANCH
          git remote add $GITHUB_PAGES_BRANCH https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/equinor/ecalc
          git add .
          git commit -m "Built from commit '$CREATED_FROM_REF'"
          git push -f --set-upstream gh-pages gh-pages
