name: Example Notebooks CI
on:
  # Workflow dispatch is used for manual triggers
  workflow_dispatch:
  # Workflow call is used for called from another workflow
  workflow_call:

jobs:
  run-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Convert example Jupyter notebooks to Python code
        run: uv run jupyter nbconvert --to python examples/*.ipynb

      # This will not log any tests per se, but it will fail if there are any errors raised in the generated Python files.
      - name: Run tests
        run: uv run pytest examples/*.py
