name: on-pull-request.yml
on:
  pull_request:

permissions: { }
jobs:
  ensure-code-quality:
    permissions:
      contents: read
    if: false # disable license scanning until we have sth we can trust, or skip altogether
    uses: ./.github/workflows/license-scan.yml

