name: Pre CI

on:
  # Workflow dispatch is used for manual triggers
  workflow_dispatch:
  # Workflow call is used for called from another workflow
  workflow_call:

jobs:
  pre-commit: # Static analyzers, formatters and verifying pre-commit hooks has been run for both API and Web
    name: Build & Run Pre Commit hooks to verify code structure, quality etc. from pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install pre-commit
        run: pip install pre-commit==3.2.2

      - name: Run pre-commit
        run: SKIP=trufflehog pre-commit run --all-files --verbose
