name: Pre CI

on:
  # Workflow dispatch is used for manual triggers
  workflow_dispatch:
  # Workflow call is used for called from another workflow
  workflow_call:

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  pre-commit: # Static analyzers, formatters and verifying pre-commit hooks has been run for both API and Web
    name: Build & Run Pre Commit hooks to verify code structure, quality etc. from pre-commit hooks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install pre-commit
        run: uv sync --only-group dev -v

      - name: Run pre-commit
        run: SKIP=trufflehog,no-commit-to-branch uv run pre-commit run --all-files --verbose
