name: Test Library
on:
  workflow_dispatch:
  workflow_call:

permissions: { }

jobs:
  test-library:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12", "3.13", "3.14" ]
        group: [ 1,2,3,4,5 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: List pydantic version
        run: uv pip show pydantic

        # TODO: Test on the installed package instead of the source code directly
        # in order to verify that the package is correctly installed
      - name: Run tests
        timeout-minutes: 10
        run: uv run python -m pytest --splits 5 --splitting-algorithm least_duration --group=${{ matrix.group }}

      - name: Build artifacts
        run: uv build

