name: Trigger External Workflow
on:
  workflow_call:
  workflow_dispatch:

permissions: {}

jobs:
    trigger-external-workflow:
      runs-on: ubuntu-24.04
      steps:
        - name: Trigger web workflow
          env:
            AUTH_TOKEN: ${{ secrets.TARGET_REPO_AUTH_TOKEN }}
            OWNER: ${{ secrets.TARGET_REPO_OWNER }}
            REPO: ${{ secrets.TARGET_REPO_NAME }}
            WORKFLOW_FILE_NAME: ${{ secrets.TARGET_REPO_WORKFLOW_FILE_NAME }}
          run: |
            curl -X POST \
            -H "Authorization: Bearer $AUTH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$OWNER/$REPO/actions/workflows/$WORKFLOW_FILE_NAME/dispatches \
            -d '{"ref":"main"}'
