name: Trigger External Workflow
on:
  workflow_call:
  workflow_dispatch:

permissions: {}

jobs:
    trigger-external-workflow:
      if: github.repository_owner == 'equinor'
      runs-on: ubuntu-24.04
      steps:
        - name: Trigger web workflow
          env:
            AUTH_TOKEN: ${{ secrets.TARGET_REPO_AUTH_TOKEN }}
            OWNER: ${{ secrets.TARGET_REPO_OWNER }}
            REPO: ${{ secrets.TARGET_REPO_NAME }}
            WORKFLOW_FILE_NAME: ${{ secrets.TARGET_REPO_WORKFLOW_FILE_NAME }}
          run: |
            curl -L -X POST \
            -H "Authorization: Bearer $AUTH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$OWNER/$REPO/actions/workflows/$WORKFLOW_FILE_NAME/dispatches \
            -d '{"event_type":"libecalcupdated", "ref":"refs/heads/main", "client_payload":{"branch": "${{ github.ref_name }}", "version":"main"}}'
