name: update-requirements.yml
on:
  workflow_call:
  push:
permissions:
  contents: write

jobs:
  update-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: 3.11

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Freeze dependencies
        run: uv export --frozen --format=requirements.txt --all-extras --no-editable > requirements.txt

      - name: Configure git
        run: |
          git config --local user.name "eCalc Update bot"
          git config --local user.email "gm_ecalc_support@equinor.com"
          
      - name: Checkout and pull
        run: |
          git checkout requirements-branch
          git pull
      - name: Commit
        run: |
          git add requirements.txt
          git commit -m "ci: update requirements.txt" || echo "No changes to commit"
      - name: Push
        run: |
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}






